services:
  - type: web
    name: dehneshin
    runtime: node
    plan: free
    buildCommand: cd server && npm install && cd ../client && npm install --include=dev && npm run build
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        value: https://dehneshin.onrender.com
